Add OPML file parsing
AngeloStavrow/rss-firehose pull request #3
Opened 2020-04-28 20:39 UTC by AngeloStavrow

This PR adds an `/opml` endpoint in **server.js** which uses **opmlparser.js** to:

1. parse the OPML file at `public/subscriptions.opml`;
2. send each feed URL to the `/api/parse/:feed` endpoints; and
3. return the JSON all feeds to the client.

You can test this by going to https://rss-firehose-parseopml.glitch.me/opml and checking out the returned JSON for the Glitch feed from Dev.to and my own feed on Dev.to — it's helpful to have a JSON viewer extension installed in your browser (Firefox Developer Edition handles JSON nicely by default).

2020-04-28 20:40 UTC, AngeloStavrow commented on opmlparser.js
> +    let counter = 0;
I don't think this needs to be here.

2020-04-29 17:36 UTC, melissamcewen requested changes
Looks great. There were a few areas I noticed no comment that I noted here, they just stood out because most other code was commented.

2020-04-29 17:36 UTC, melissamcewen commented on server.js
> +app.get("/opml", async function(request, response) {
Add comment

2020-04-29 17:36 UTC, melissamcewen commented on opmlparser.js
> +    opmlparser.on("readable", function () {
Add comment

2020-04-29 19:26 UTC, merged